# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: steammessages_timedtrial.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'steammessages_timedtrial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import steammessages_base_pb2 as steammessages__base__pb2
import steammessages_unified_base_pb2 as steammessages__unified__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esteammessages_timedtrial.proto\x1a\x18steammessages_base.proto\x1a steammessages_unified_base.proto\"5\n$CTimedTrial_GetTimeRemaining_Request\x12\r\n\x05\x61ppid\x18\x01 \x01(\r\"\x84\x01\n%CTimedTrial_GetTimeRemaining_Response\x12\x16\n\x0eseconds_played\x18\x01 \x01(\r\x12\x17\n\x0fseconds_allowed\x18\x02 \x01(\r\x12\x11\n\tpackageid\x18\x03 \x01(\r\x12\x17\n\x0fmastersub_appid\x18\x04 \x01(\r\"K\n\"CTimedTrial_RecordPlaytime_Request\x12\r\n\x05\x61ppid\x18\x01 \x01(\r\x12\x16\n\x0eseconds_played\x18\x02 \x01(\r\"V\n#CTimedTrial_RecordPlaytime_Response\x12\x16\n\x0eseconds_played\x18\x01 \x01(\r\x12\x17\n\x0fseconds_allowed\x18\x02 \x01(\r\"2\n!CTimedTrial_ResetPlaytime_Request\x12\r\n\x05\x61ppid\x18\x01 \x01(\r\"U\n\"CTimedTrial_ResetPlaytime_Response\x12\x16\n\x0eseconds_played\x18\x01 \x01(\r\x12\x17\n\x0fseconds_allowed\x18\x02 \x01(\r2\x9b\x04\n\nTimedTrial\x12\xad\x01\n\x10GetTimeRemaining\x12%.CTimedTrial_GetTimeRemaining_Request\x1a&.CTimedTrial_GetTimeRemaining_Response\"J\x82\xb5\x18\x46Returns the amount of time a user has left on a timed trial for an app\x12\x94\x01\n\x0eRecordPlaytime\x12#.CTimedTrial_RecordPlaytime_Request\x1a$.CTimedTrial_RecordPlaytime_Response\"7\x82\xb5\x18\x33Updates the user\'s remaining playtime while in game\x12\x92\x01\n\rResetPlaytime\x12\".CTimedTrial_ResetPlaytime_Request\x1a#.CTimedTrial_ResetPlaytime_Response\"8\x82\xb5\x18\x34Reset the user\'s remaining playtime (developer only)\x1a\x31\x82\xb5\x18-A service to get user timed trial informationB\x03\x90\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'steammessages_timedtrial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_TIMEDTRIAL']._loaded_options = None
  _globals['_TIMEDTRIAL']._serialized_options = b'\202\265\030-A service to get user timed trial information'
  _globals['_TIMEDTRIAL'].methods_by_name['GetTimeRemaining']._loaded_options = None
  _globals['_TIMEDTRIAL'].methods_by_name['GetTimeRemaining']._serialized_options = b'\202\265\030FReturns the amount of time a user has left on a timed trial for an app'
  _globals['_TIMEDTRIAL'].methods_by_name['RecordPlaytime']._loaded_options = None
  _globals['_TIMEDTRIAL'].methods_by_name['RecordPlaytime']._serialized_options = b'\202\265\0303Updates the user\'s remaining playtime while in game'
  _globals['_TIMEDTRIAL'].methods_by_name['ResetPlaytime']._loaded_options = None
  _globals['_TIMEDTRIAL'].methods_by_name['ResetPlaytime']._serialized_options = b'\202\265\0304Reset the user\'s remaining playtime (developer only)'
  _globals['_CTIMEDTRIAL_GETTIMEREMAINING_REQUEST']._serialized_start=94
  _globals['_CTIMEDTRIAL_GETTIMEREMAINING_REQUEST']._serialized_end=147
  _globals['_CTIMEDTRIAL_GETTIMEREMAINING_RESPONSE']._serialized_start=150
  _globals['_CTIMEDTRIAL_GETTIMEREMAINING_RESPONSE']._serialized_end=282
  _globals['_CTIMEDTRIAL_RECORDPLAYTIME_REQUEST']._serialized_start=284
  _globals['_CTIMEDTRIAL_RECORDPLAYTIME_REQUEST']._serialized_end=359
  _globals['_CTIMEDTRIAL_RECORDPLAYTIME_RESPONSE']._serialized_start=361
  _globals['_CTIMEDTRIAL_RECORDPLAYTIME_RESPONSE']._serialized_end=447
  _globals['_CTIMEDTRIAL_RESETPLAYTIME_REQUEST']._serialized_start=449
  _globals['_CTIMEDTRIAL_RESETPLAYTIME_REQUEST']._serialized_end=499
  _globals['_CTIMEDTRIAL_RESETPLAYTIME_RESPONSE']._serialized_start=501
  _globals['_CTIMEDTRIAL_RESETPLAYTIME_RESPONSE']._serialized_end=586
  _globals['_TIMEDTRIAL']._serialized_start=589
  _globals['_TIMEDTRIAL']._serialized_end=1128
_builder.BuildServices(DESCRIPTOR, 'steammessages_timedtrial_pb2', _globals)
# @@protoc_insertion_point(module_scope)
