# Permission bit flags for admin operations
EDIT_ADMINS = 1 << 0
EDIT_USERS = 1 << 1
CONFIG_EDIT = 1 << 2
SERVER_LIST_EDIT = 1 << 3
FTP_APPROVAL = 1 << 4
FTP_USER_MANAGE = 1 << 5
SUBSCRIPTION_EDIT = 1 << 6
CHATROOM_MANAGE = 1 << 7
CLAN_MANAGE = 1 << 8
NEWS_MANAGE = 1 << 9
LICENSE_MANAGE = 1 << 10
TOKEN_MANAGE = 1 << 11
INVENTORY_EDIT = 1 << 12
ALL_PERMISSIONS = (
    EDIT_ADMINS | EDIT_USERS | CONFIG_EDIT |
    SERVER_LIST_EDIT | FTP_APPROVAL |
    FTP_USER_MANAGE | SUBSCRIPTION_EDIT |
    CHATROOM_MANAGE | CLAN_MANAGE |
    NEWS_MANAGE | LICENSE_MANAGE |
    TOKEN_MANAGE | INVENTORY_EDIT
)
