PERM_PURCHASE                = 1 << 0
PERM_SEND_GUEST_PASSES       = 1 << 1
PERM_CHANGE_EMAIL            = 1 << 2
PERM_CHANGE_PASSWORD         = 1 << 3
PERM_CHANGE_SECURITY_QUESTION= 1 << 4
PERM_REGISTER_CDKEYS         = 1 << 5
PERM_LAUNCH_APPLICATIONS     = 1 << 6
PERM_LOGIN                   = 1 << 7
PERM_ADD_FRIENDS             = 1 << 8
PERM_RECEIVE_FRIEND_REQUESTS = 1 << 9
PERM_CREATE_CLANS            = 1 << 10
PERM_CREATE_GROUPS           = 1 << 11
PERM_JOIN_CLANS              = 1 << 12
PERM_JOIN_GROUPS             = 1 << 13
PERM_MUTE_FRIENDS            = 1 << 14
PERM_RUN_SERVER              = 1 << 15
PERM_JOIN_GAMES              = 1 << 16
PERM_CREATE_LOBBY            = 1 << 17
